// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// 初始化检测器
///
/// # Arguments
/// * `config_json` - JSON 格式的配置，空字符串则使用默认配置
///
/// # Returns
/// 成功返回 true
Future<bool> initDetector({required String configJson}) =>
    RustLib.instance.api.crateApiInitDetector(configJson: configJson);

/// 处理单张图片（返回 JSON 字符串）
///
/// # Arguments
/// * `image_path` - 图片文件路径
/// * `options_json` - 处理选项（JSON 格式，空字符串使用默认选项）
///
/// # Returns
/// JSON 格式的完整检测结果
Future<String> processImage({required String imagePath, required String optionsJson}) =>
    RustLib.instance.api.crateApiProcessImage(imagePath: imagePath, optionsJson: optionsJson);

/// 批量处理多张图片
///
/// # Arguments
/// * `image_paths_json` - 图片路径列表（JSON 数组格式）
/// * `options_json` - 处理选项
///
/// # Returns
/// JSON 格式的检测结果数组
Future<String> processBatch({required String imagePathsJson, required String optionsJson}) =>
    RustLib.instance.api.crateApiProcessBatch(imagePathsJson: imagePathsJson, optionsJson: optionsJson);

/// 获取默认配置（JSON 格式）
Future<String> getDefaultConfig() => RustLib.instance.api.crateApiGetDefaultConfig();

/// 获取版本信息
Future<String> getVersion() => RustLib.instance.api.crateApiGetVersion();

/// 释放检测器资源
Future<bool> disposeDetector() => RustLib.instance.api.crateApiDisposeDetector();

/// 处理单张图片并返回结构化结果（推荐使用此 API）
///
/// 相比 `process_image`，此函数直接返回结构体，
/// flutter_rust_bridge 会自动映射为 Dart 类，无需手动 JSON 解析。
Future<SimpleDetectionResult> processImageSimple({required String imagePath, required bool includeDebug}) =>
    RustLib.instance.api.crateApiProcessImageSimple(imagePath: imagePath, includeDebug: includeDebug);

/// 简化的检测结果（直接通过 FRB 传递给 Dart，无需 JSON 中间层）
class SimpleDetectionResult {
  final bool success;
  final int questionCount;
  final PlatformInt64 processingTimeMs;
  final List<SimpleQuestionBox> questions;
  final String? errorMessage;

  const SimpleDetectionResult({
    required this.success,
    required this.questionCount,
    required this.processingTimeMs,
    required this.questions,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      questionCount.hashCode ^
      processingTimeMs.hashCode ^
      questions.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimpleDetectionResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          questionCount == other.questionCount &&
          processingTimeMs == other.processingTimeMs &&
          questions == other.questions &&
          errorMessage == other.errorMessage;
}

/// 简化的题目框
class SimpleQuestionBox {
  final String questionId;
  final double x;
  final double y;
  final double width;
  final double height;
  final double confidence;

  const SimpleQuestionBox({
    required this.questionId,
    required this.x,
    required this.y,
    required this.width,
    required this.height,
    required this.confidence,
  });

  @override
  int get hashCode =>
      questionId.hashCode ^ x.hashCode ^ y.hashCode ^ width.hashCode ^ height.hashCode ^ confidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimpleQuestionBox &&
          runtimeType == other.runtimeType &&
          questionId == other.questionId &&
          x == other.x &&
          y == other.y &&
          width == other.width &&
          height == other.height &&
          confidence == other.confidence;
}
